### ISSUE TITLE
FMT模型编译报错

### ISSUE THREAD

**Issue by lwxtp1985** [FirmamentPilot/FMT_Model#1]
您好：

我对您这个模型进行了仿真编译，但是会报错误，显示信息如下：
![image](https://user-images.githubusercontent.com/57937035/93194988-493d1780-f77b-11ea-9a26-c368c0dad850.png)

请问怎么解决，谢谢！

**Comment by JcZou** [comment]
你框起来的部分不像是错误。你可以检查一下Pilot_Cmd模块，如果是选择的Joystick，则需要接游戏手柄（USB），或者选择Mavlink的话，则要接飞控，并且飞控的FMT_OUTPUT_PILOT_CMD宏有打开。

**Comment by lwxtp1985** [comment]
> 你框起来的部分不像是错误。你可以检查一下Pilot_Cmd模块，如果是选择的Joystick，则需要接游戏手柄（USB），或者选择Mavlink的话，则要接飞控，并且飞控的FMT_OUTPUT_PILOT_CMD宏有打开。

邹工，您好。

我接上了手柄，但是仍然报错，不知道接上手柄后是否需要在模型里面设置什么端口连接信息？另外，我用的是2019b版本的matlab，不知道会不会有影响，报错的整个信息截图如下，提示在'Controller'模块生成时有问题 ，还请帮忙再指导下，谢谢！

![image](https://user-images.githubusercontent.com/57937035/93413235-608e1900-f8d1-11ea-8cba-7b866300ea65.png)

**Comment by JcZou** [comment]
不太清楚具体是什么问题导致，这里错误的提示也很模糊。有可能是matlab编译器配置的原因，以下是我的编译器配置（matlab安装默认配置）
>> mex -setup
MEX configured to use 'Microsoft Visual C++ 2015 (C)' for C language compilation.
如果还是有问题建议切换到matlab2018b
