### ISSUE TITLE
仿真的时候3Ddisplay 里飞机没有动。

### ISSUE THREAD

**Issue by wenzhicode** [FirmamentPilot/FMT_Model#3]
您好。
仿真的时候，需要解锁指令的吗？
我连上遥控器，RC模块里能正常显示摇杆值, Data inspector能看到摇杆值曲线，不过3Ddisplay里飞机没动，Data inspector里其他变量也没有变化。

![image](https://user-images.githubusercontent.com/22004867/95281367-8e8bcb00-0889-11eb-84ad-c571d639bf62.png)

编译的时候提示输入输出端口数不匹配，我改了下这个，把5改为8，这个应该不影响吧
![image](https://user-images.githubusercontent.com/22004867/95281541-0659f580-088a-11eb-860c-d9fe9af71dd6.png)

**Comment by JcZou** [comment]
![image](https://user-images.githubusercontent.com/18414991/95298460-68abf980-087c-11eb-96ea-036bbb91e97a.png)

Joystick Input模块要选中如上所示的选项，输出的size就是5了。如果为8可能会导致yaw通道输出一些异常值。建议拉取一下我昨天最新push的修改，包含了一些问题的优化。

另外是需要解锁的，模型运行起来后，将**油门杆(左边摇杆)打到最低维持，然后右边摇杆打到左下角再回中，这时进入怠速状态，推高油门，即进入解锁状态**

**Comment by wenzhicode** [comment]
![image](https://user-images.githubusercontent.com/22004867/95300714-20a7c980-08b2-11eb-92f3-4463addb17f6.png)
![image](https://user-images.githubusercontent.com/22004867/95300769-32896c80-08b2-11eb-95d2-e2b51ed64713.png)

拉取下来，没改，我看上图的选项已经选上了。编译提示输入输出不匹配，可能是我这边遥控问题
我改成8，编译正常，现在也能起飞了。

有个问题请教下：
将3D_visualizeion 的3d display 改为flightgear, 要修改哪个参数呢，没找到

**Comment by JcZou** [comment]
右键点选*3D_Visualization*模块，选择`Variant->Label Model Active Choice`进行选择。如果选择flight gear的话，需要打开一个Flight gear的模型（比如F450）。

**Comment by wenzhicode** [comment]
好的，可以了。
