### ISSUE TITLE
关于PID

### ISSUE THREAD

**Issue by wenzhicode** [FirmamentPilot/FMT_Model#4]
您好。

我看Control 模块中的PID是P/I/D分别进行计算的，是为了要对D值进行滤波吗？ 这里能不能直接使用simulink自带的PID controller呢？
另外，在Veloxity_Z_Controller中的PID后boosted throttle模块根据姿态角进行输出限制，是对油门值进行补偿，防止掉高么

谢谢

**Comment by JcZou** [comment]
PID本来就是要分别进行计算的。 bootsted_throtlle是为了在飞机倾斜的时候对油门进行补偿，防止掉高

**Comment by JcZou** [comment]
当然也是可以直接使用simulink自带的PID

**Comment by wenzhicode** [comment]
好的，谢谢
